FROM mcr.microsoft.com/dotnet/sdk:8.0 as build
WORKDIR /source
COPY . .
RUN find . \( -name "bin" -o -name "obj" \) -type d -exec rm -rf {} +
RUN dotnet build -c:Release
WORKDIR /source/Client/bin/x64/Release/net9.0
ENTRYPOINT [ "./Client" ]